export const MODELS = {
	mousepad:
		"https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/MOUSEPAD_01.obj",
	pillow:
		"https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/Pillow.obj",
	termo:
		"https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/uploads_files_2344119_final.obj",
	shirt:
		"https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/shirt.obj",
	shirts:
		"https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/uploads_files_2488279_Top%2B13.obj",
    bottle:
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/mirai.obj",
	frasco:
	"https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/oil_bottle_001.obj",
	frasco2:
	"https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/Plastic%20Water%20Bottle%20Empty.obj",
	pad:
	"https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/mouse_pad.obj",
	botellaChida:
	"https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/Plastic%20Water%20Bottle%20Full.obj"
};