export const BACKGROUNDS = {
    museo: [
        "https://threejsfundamentals.org/threejs/resources/images/cubemaps/computer-history-museum/pos-x.jpg",
        "https://threejsfundamentals.org/threejs/resources/images/cubemaps/computer-history-museum/neg-x.jpg",
        "https://threejsfundamentals.org/threejs/resources/images/cubemaps/computer-history-museum/pos-y.jpg",
        "https://threejsfundamentals.org/threejs/resources/images/cubemaps/computer-history-museum/neg-y.jpg",
        "https://threejsfundamentals.org/threejs/resources/images/cubemaps/computer-history-museum/pos-z.jpg",
        "https://threejsfundamentals.org/threejs/resources/images/cubemaps/computer-history-museum/neg-z.jpg",
    ],
    muelle: [        
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/Muelle/posx.png",
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/Muelle/negx.png",
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/Muelle/posy.png",
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/Muelle/negy.png",
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/Muelle/posz.png",
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/Muelle/negz.png",
    ],
    casa: [
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/Home/posx.png",
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/Home/negx.png",
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/Home/posy.png",
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/Home/negy.png",
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/Home/posz.png",
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/Home/negz.png",
    ],
    sala: [
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/Sala/posx.png",
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/Sala/negx.png",
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/Sala/posy.png",
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/Sala/negy.png",
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/Sala/posz.png",
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/Sala/negz.png",
    ],
    草: [
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/Pasto/posx.png",
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/Pasto/negx.png",
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/Pasto/posy.png",
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/Pasto/negy.png",
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/Pasto/posz.png",
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/Pasto/negz.png",
    ],
    atardecer: [
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/atardecer/posx.png",
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/atardecer/negx.png",
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/atardecer/posy.png",
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/atardecer/negy.png",
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/atardecer/posz.png",
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/atardecer/negz.png",
    ],
    selva: [
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/Selva/posx.png",
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/Selva/negx.png",
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/Selva/posy.png",
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/Selva/negy.png",
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/Selva/posz.png",
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/Selva/negz.png",
    ],
    estudio: [
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/Studio/posx.png",
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/Studio/negx.png",
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/Studio/posy.png",
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/Studio/negy.png",
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/Studio/posz.png",
        "https://raw.githubusercontent.com/ManmadeArc/GraficasYVisualizacion/main/BG/Studio/negz.png",
    ],
}